using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Solution_2
{
    class Program
    {
        static void Main(string[] args)
        {
            // Problem - 2
            /*
             * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
             * the first 10 terms will be:
             *
             * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
             *
             * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
             */
            int number = 1;
            int number2 = 0;
            int fibonacci = 0;
            int finish = 4000000;
            int total = 0;
            while (fibonacci < finish)
            {
                fibonacci = number + number2;
                number2 = number;
                number = fibonacci;
                if (fibonacci % 2 == 0)
                {
                    total += fibonacci;
                }
            }
            Console.WriteLine("Answer = {0}", total);
            Console.ReadKey();
        }
    }
}
